### ISSUE TITLE
Unexpected sorting info line

### ISSUE THREAD

**Issue by FredWanninger** [siddhantgoel/beancount-ing-diba#65]
Hi,

my ING CSV exports contain a header line that says something about sort order.
```
...
Saldo;XX,XX;EUR

Sortierung;Datum absteigend   <= HERE

In der CSV-Datei finden Sie alle bereits gebuchten Umsätze. Die vorgemerkten Umsätze werden nicht aufgenommen, auch wenn sie in Ihrem Internetbanking angezeigt werden.
...
```
This line seems to be unexpected in your importer. 
https://github.com/siddhantgoel/beancount-ing-diba/blob/5a23c2bcf23cf7d69232d10c3786a42d89ea5b59/beancount_ing_diba/ec.py#L171-L179
Could you please check this?

Thanks and regards
Fred

**Comment by siddhantgoel** [comment]
Yep, this was bugging me for a while now too. Just pushed `v0.2.1` which should fix this.

**Comment by FredWanninger** [comment]
Problem solved. Thank you!
