### ISSUE TITLE
Category not represented

### ISSUE THREAD

**Issue by anpr** [siddhantgoel/beancount-ing-diba#67]
Hi,

For me the importer only worked after I added the "Category" field. I think it's only active if you activated the "Analyse" as a user. Would be nice to have the option to activate/deactivate it.

Moreover, it's possible to download CSVs that don't have a Balance (Saldo), but this importer expects it to be there. Would be nice to mention this in the docs.

**Comment by siddhantgoel** [comment]
Hey, yes the balance thing is known but I haven't had time to fix it yet. I'll try to find time for both these issues over the weekend. PRs are also welcome though. :)

**Comment by szabootibor** [comment]
Hi,

I have the issue too. I think it would be possible to ignore unexpected extra columns, so that it is transparent for the user.

Recently I have used pandas.DataFrame to deal with table data from csv in beancount importers. DataFrame is an excellent tool and also not very difficult to use. Here is an example: https://github.com/Dr-Nuke/drnuke-bean/blob/master/src/drnukebean/importer/ibkr.py

Are you interested in using DataFrame for processing ING's csv? I could integrate it into the ING-DiBa importer, if you wish.

**Comment by siddhantgoel** [comment]
Hey, I just had another look at this. Looks like switching to `csv.DictReader` should already be enough to make this handling of categories transparent.

I have this change in the [categories](https://github.com/siddhantgoel/beancount-ing-diba/compare/categories) branch which seems to work. I'll try to merge it into the main branch over the next days and will push another release. Just added a TODO item on my list for this.

**Comment by szabootibor** [comment]
@siddhantgoel thank you for your effort!

I have also noticed that the "second header" `;Letztes Update: aktuell` checked by `_is_valid_second_header` is not present anymore in the export. I see it in a CSV from 2021-04-02 but not in the CSVs from 2021-04-24 or later. Do you need a fix for this?

**Comment by siddhantgoel** [comment]
Oh yeah, I haven't downloaded an export from April yet, but if you see it's not there anymore please consider submitting a PR to make it optional. Thank you!

I wonder if implementing this is related to the proposal [here](https://github.com/siddhantgoel/beancount-ing-diba/issues/69#issuecomment-829566498) (of reading the file segment by segment, successive segments split by empty lines)?

**Comment by szabootibor** [comment]
No, I think these are independent from each other. The #69 started though as *The `Saldo` metadata entry should be made optional.*, but actually it *is* handled as optional.

**Comment by siddhantgoel** [comment]
@anpr please upgrade to `v0.4.0` which supports this extra "Kategorie" field as well.

**Comment by anpr** [comment]
Thanks 🙏

**Comment by siddhantgoel** [comment]
Resolved in `v0.4.0`.
