### ISSUE TITLE
How to use it exactly

### ISSUE THREAD

**Issue by r2p2** [siddhantgoel/beancount-ing-diba#68]
Sorry for bothering you with the maybe simple question but I've just started to use beancount and its documentation about importers does not help me much. In the usage section of your importer project, you just posted a small python script which contains an import and an example configuration array. But I don't know where to put this file and it does not tell me how it is executed.

Could you clarify this eventually?

Thank you in advance.

**Comment by siddhantgoel** [comment]
Sure, no worries. You'll first need to download a CSV export of your transactions from https://www.ing.de/ and put it somewhere on disk. I have this setup in a local python project with roughly the following layout.

```
(3.8.5/envs/finances) siddhant@thinkpad ~/Work/finances % tree .
.
├── config.py
├── my.beancount
├── originals
│   ├── ing-diba
│   │   ├── 2019
│   │   │   └── 01-jan.csv
│   │   │   └── 02-feb.csv
│   │   │   └── ...
```

All the CSV files I download go inside the `originals/` directory.

The script I posted in the Usage section goes inside `config.py`. Assuming you have a local virtualenv with `beancount` and `beancount-ing-diba` installed, you should be able to run `bean-extract config.py /path/to/your/export.csv` and Beancount will read your transactions from the CSV file, parse them into the beancount format and print them all on screen. Normally you'd want to pipe them to your beancount file (using `bean-extract config.py /path/to/your/export.csv >> my.beancount`).

From that point onwards, your ING transactions should be in the Beancount format and you can go ahead with the regular Beancount workflow.

**Comment by siddhantgoel** [comment]
I'll mark this issue as closed. If you have a follow-up question, feel free to reopen.
